### ISSUE TITLE
Support UUID type

### ISSUE THREAD

**Issue by Yak000** [mhewedy/spring-data-jpa-mongodb-expressions#26]
I'm trying to use the plugin to search some UUID fields but it looks like the fields are not properly translated from the request string to JPA UUID

Am I missing something?

**Comment by mhewedy** [comment]
Issue [fixed](https://github.com/mhewedy/spring-data-jpa-mongodb-expressions/commit/88e7beb44ecce6d4d28808c00b5da507020d65b7) and will be part of the next release ([milestone 0.0.4](https://github.com/mhewedy/spring-data-jpa-mongodb-expressions/milestone/2)).

Please give a look at the [test case](https://github.com/mhewedy/spring-data-jpa-mongodb-expressions/blob/88e7beb44ecce6d4d28808c00b5da507020d65b7/src/test/java/com/github/mhewedy/expressions/ExpressionsRepositoryImplTest.java#L551) to see if it suits your needs 

Please let me know if you urgently need this issue released, as I can do an urgent release if required.

**Comment by Yak000** [comment]
Yes looks like it should do it! Thx

Would be nice to have it asap as we won't need to change the database UUID fields to String

**Comment by mhewedy** [comment]
Version **0.0.4** has been released with the fix. It usually takes a couple of hours and becomes available.
