### ISSUE TITLE
create new release support spring 6 (java ee 9) with jakarta namespace

### ISSUE THREAD

**Issue by mhewedy** [mhewedy/spring-data-jpa-mongodb-expressions#31]
the current implementation is compatible with spring 6 (spring boot 3), except for renaming `javax.persistence` to `jakarta.persistence` ..

**Comment by motazco135** [comment]
When I try  spring boot 3.0.1 I faced other issues related to add spring boot validation to my pom.xml 
I think if you use IntelliJ IDEA they have released migration tool that will help you a lot 
[Migration support in IntelliJ IDEA](https://blog.jetbrains.com/idea/2021/06/intellij-idea-eap-6/) .
`
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
`

**Comment by mhewedy** [comment]
> When I try spring boot 3.0.1 I faced other issues related to add spring boot validation to my pom.xml I think if you use IntelliJ IDEA they have released migration tool that will help you a lot [Migration support in IntelliJ IDEA](https://blog.jetbrains.com/idea/2021/06/intellij-idea-eap-6/) . `<dependency> <groupId>org.springframework.boot</groupId> <artifactId>spring-boot-starter-validation</artifactId> </dependency>`

Thanks @motazco135 🤩

I did the upgrade couple of days back. It was simple.
Now starting from 0.1.0 the library supports sp 3.0

And thnaks for sharing the link for intellij migration tool. It will help in other projects as well. 🌹
